# Generated by Django 5.1.4 on 2024-12-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='message', max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('affectedpeoples', models.CharField(default='affectedpeoples', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.userdetails')),
            ],
        ),
    ]
