# Generated by Django 5.1.4 on 2024-12-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_crisisreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisreports',
            name='disasterimage',
            field=models.ImageField(blank=True, null=True, upload_to='disasters/'),
        ),
    ]
