# Generated by Django 5.1.4 on 2024-12-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_admindetails_crisisreporting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='location', max_length=50)),
                ('message', models.CharField(default='message', max_length=40)),
                ('vacancy', models.CharField(default='vacancy', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
