# Generated by Django 5.1.4 on 2025-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_remove_volunteerdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='location',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='aadhar_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_files/'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='district',
            field=models.CharField(default='district', max_length=50),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(default='abv', max_length=10),
        ),
    ]
