# Generated by Django 5.1.4 on 2025-01-24 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_remove_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
