# Generated by Django 5.1.4 on 2025-01-24 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_jobdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisreporting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
