# Generated by Django 5.1.4 on 2025-01-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
