# Generated by Django 5.1.4 on 2025-01-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_donationrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='adminapprove',
            field=models.BooleanField(default=False),
        ),
    ]
