# Generated by Django 5.1.4 on 2025-01-30 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0014_donationrequest_adminapprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='adminapprove',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
