# Generated by Django 5.1.4 on 2025-01-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_donationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=20)),
            ],
        ),
    ]
