# Generated by Django 5.1.4 on 2025-01-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_admindonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admindonation',
        ),
    ]
