# Generated by Django 5.1.4 on 2025-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_admindonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindonation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='admindonation',
            name='recieved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
