# Generated by Django 5.1.4 on 2025-01-31 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0022_alter_donationvolunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationvolunteer',
            name='item_name',
        ),
    ]
