# Generated by Django 5.1.4 on 2025-01-31 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0023_remove_donationvolunteer_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationvolunteer',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.admindonation'),
        ),
    ]
