# Generated by Django 5.1.4 on 2025-01-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0024_donationvolunteer_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationvolunteer',
            name='adminapprove',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
