# Generated by Django 5.1.4 on 2025-02-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0025_donationvolunteer_adminapprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
