# Generated by Django 5.1.4 on 2025-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0027_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisreporting',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crisisreporting',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
