# Generated by Django 5.1.4 on 2025-02-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0028_crisisreporting_lat_crisisreporting_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteerdetails',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteerdetails',
            name='pincode',
            field=models.CharField(default='abv', max_length=6),
        ),
    ]
