from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',views.index,name="home"),
    path('register/',views.register),
    path('login/',views.userlogin,name="login"),
    path('admins/',views.admins,name="admins"),
    path('user/',views.user_view,name="user"),
    path('volunteer/',views.volunteer,name="volunteer"),
    # path('userlogin/',views.userlogin,name="userlogin"),
    path('userdashboard/',views.userdashboard,name="userdashboard"),
    path('volunteerlogin/',views.volunteerlogin_view,name="volunteerlogin"),
    path('volunteerdashboard/',views.volunteerdashboard_view,name="volunteerdashboard"),
    path('crisis/',views.crisis,name="crisis"),
    path('volunteerhelp/',views.volunteerhelp,name="volunteerhelp"),
    path('crisisreporting/',views.crisisreporting,name="crisisreporting"),
    path('logout/',views.logout,name="logout"),
    path('resourcerequest/',views.resourcerequest,name="resourcerequest"),
    path('users/',views.users,name="users"),
    path('volunteers/',views.volunteers,name="volunteers"),
    path('crisisreports/',views.crisisreports,name="crisisreports"),
    path('logout/',views.logout,name="logout"),
    path('admin_login/', views.admin_login, name='admin_login'),    
    path('admindashboard/',views.admindashboard,name="admindashboard"),
    path('add/',views.add,name="add"),
    path('approve/',views.approve,name="approve"),
    path('view/',views.view,name="view"),
    path('volunteercrisis/',views.volunteercrisis,name="volunteercrisis"),
    path('volunteercrisisreporting/',views.volunteercrisisreporting,name="volunteercrisisreporting"),
    path('crisisvolunteer/',views.crisisvolunteer,name="crisisvolunteer"),
    path('adminreport/',views.adminreport,name="adminreport"),
    path('userprofile/',views.userprofile, name='userprofile'),
    path('volunteerprofile/',views.volunteerprofile, name='volunteerprofile'),
    path('useredit/',views.useredit, name='useredit'),
    path('volunteeredit/',views.volunteeredit, name='volunteeredit'),
    path('volunteerdonation/<int:post_id>/',views.volunteerdonation, name='volunteerdonation'),
    path('userdonation/',views.userdonation, name='userdonation'),
    path('jobs/',views.jobs_view,name="jobs"),
    path('job/',views.job,name="job"),
    path('adminjob/',views.adminjob,name="adminjob"),
    path('adminreport/',views.adminreport,name="adminreport"),
    path('job/accept/<int:job_id>/',views.accept_job, name='accept_job'),  # URL for accepting job
    path('job/reject/<int:job_id>/',views.reject_job, name='reject_job'),

    ## job requests
    path('job-approve-volunteer/<int:job_id>/',views.job_approve_volunteer, name='job_approve_volunteer'),
    path('job-reject-volunteer/<int:job_id>/',views.job_reject_volunteer, name='job_reject_volunteer'),
    path('job-list/',views.joblist, name='job_list'),
    path('admin-list-applications/<int:job_id>/',views.admin_list_job_applications, name='admin_list_job_applications'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('delete_volunteer/<int:id>/', views.delete_volunteer, name='delete_volunteer'),
    path('user-list/',views.userlist, name='user_list'),
    path('donationrequest/',views.admindonation, name='donationrequest'),
    path('accept_donations/<int:donation_id>/',views.accept_donations, name='accept_donations'),
    path('reject_donations/<int:donation_id>/',views.reject_donations, name='reject_donations'),
    path('admindonate/',views.admindonate, name='admindonate'),
    path('add_donationpost/',views.admindonateadd, name='add_donationpost'),
    path('donationrequestvolunteer/',views.donationrequestvolunteer, name='donationrequestvolunteer'),
    path('accept_donationvolunteer/<int:donation_id>/',views.accept_donationvolunteer, name='accept_donationvolunteer'),
    path('reject_donationvolunteer/<int:donation_id>/',views.reject_donationvolunteer, name='reject_donationvolunteer'),
    path('password_reset/',views.password_reset, name='password_reset'),
    path('volunteerlist/',views.volunteerlist, name='volunteerlist'),
    path('volunteerregister/',views.volunteerregister, name='volunteerregister'),
    path('verify_otp/<int:otp_id>/',views.verify_otp, name='verify_otp'),
    path('set_new_password/<int:pk>/',views.set_new_password, name='set_new_password'),
    path('chatbot/',views.chatbot, name='chatbot'),
    path('location/<int:re_id>/',views.location, name='location'),
    path('delete_user/<int:user_id>/',views.delete_user, name='delete_user'),
    path('crisisreportinguser/',views.crisisreportinguser,name="crisisreportinguser"),
    path('delete_volunteers/<int:volunteer_id>/',views.delete_volunteers, name='delete_volunteers'),
    path('registervolunteer/',views.registervolunteer, name='registervolunteer'),
    path('success/', views.success_page, name='success_page'),
    path('crisissuccess/',views.crisissuccess,name="crisissuccess"),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
